version: "0.5"

processes:
  temporal:
    command: go build -o side-temporal ./cmd/temporal && SIDE_LOG_LEVEL=0 SIDE_APP_ENV=development ./side-temporal

  api:
    command: go build -o side-api ./api/main && SIDE_LOG_LEVEL=0 SIDE_APP_ENV=development ./side-api

  worker:
    command: go build -o side-worker ./worker/main && SIDE_LOG_LEVEL=0 SIDE_APP_ENV=development ./side-worker

  frontend:
    command: bun dev
    working_dir: frontend