version: '3'

# ensure the dev task kills other deps if any fail
failfast: true

tasks:
  dev:
    desc: Run all services concurrently for local development
    deps: [temporal, api, worker, frontend]

  temporal:
    desc: Run the Temporal server
    cmds:
      - go build -o temporalbin ./cmd/temporal && ./temporalbin
    watch: true
    sources:
      - temporal/**/*.go

  api:
    desc: Run the API server
    cmds:
      - go build -o apibin ./api/main && ./apibin
    watch: true
    sources:
      - "**/*.go"
      - go.mod
      - go.sum

  worker:
    desc: Run the worker server
    cmds:
      - go build -o workerbin ./worker/main && ./workerbin
    watch: true
    sources:
      - "**/*.go"
      - go.mod
      - go.sum

  frontend:
    desc: Run the frontend dev server
    dir: frontend
    watch: true
    sources:
      - frontend/package.json
      - frontend/bun.lock
    cmds:
      - bun dev