// Code generated by mockery v2.36.0. DO NOT EDIT.
// NOTE had to edit to make it work, see NOTE below for details of the edit.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	/*
	 * NOTE had to edit this import to get it to work since it used internal
	 * package, and replaced all instances of internal with client below.
	 * otherwise, we get the following error:
	 *
	 *     mocks/temporal_schedule_client.go:9:2: use of internal package go.temporal.io/sdk/internal not allowed
	 */
	//internal "go.temporal.io/sdk/internal"
	client "go.temporal.io/sdk/client"
)

// ScheduleClient is an autogenerated mock type for the ScheduleClient type
type ScheduleClient struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, options
func (_m *ScheduleClient) Create(ctx context.Context, options client.ScheduleOptions) (client.ScheduleHandle, error) {
	ret := _m.Called(ctx, options)

	var r0 client.ScheduleHandle
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, client.ScheduleOptions) (client.ScheduleHandle, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.ScheduleOptions) client.ScheduleHandle); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.ScheduleHandle)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.ScheduleOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHandle provides a mock function with given fields: ctx, scheduleID
func (_m *ScheduleClient) GetHandle(ctx context.Context, scheduleID string) client.ScheduleHandle {
	ret := _m.Called(ctx, scheduleID)

	var r0 client.ScheduleHandle
	if rf, ok := ret.Get(0).(func(context.Context, string) client.ScheduleHandle); ok {
		r0 = rf(ctx, scheduleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.ScheduleHandle)
		}
	}

	return r0
}

// List provides a mock function with given fields: ctx, options
func (_m *ScheduleClient) List(ctx context.Context, options client.ScheduleListOptions) (client.ScheduleListIterator, error) {
	ret := _m.Called(ctx, options)

	var r0 client.ScheduleListIterator
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, client.ScheduleListOptions) (client.ScheduleListIterator, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.ScheduleListOptions) client.ScheduleListIterator); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.ScheduleListIterator)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.ScheduleListOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewScheduleClient creates a new instance of ScheduleClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewScheduleClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ScheduleClient {
	mock := &ScheduleClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
