// Lexicographic rank keys over the lowercase a-z alphabet, used for
// fine-grained ordering (e.g. projects within a priority bucket).

// midString returns a string strictly between prev and next in lexicographic
// order. An empty prev means "before everything" and an empty next means
// "after everything". Generated keys never end in 'a', which guarantees a
// midpoint always exists between any two keys produced by this function.
// Callers must only pass keys generated by this function (or empty strings).
export function midString(prev: string, next: string): string {
  let p = 0
  let n = 0
  let pos: number
  // find leftmost non-matching character, using sentinels just outside the
  // a-z range for exhausted strings
  for (pos = 0; p === n; pos++) {
    p = pos < prev.length ? prev.charCodeAt(pos) : 96
    n = pos < next.length ? next.charCodeAt(pos) : 123
  }
  let str = prev.slice(0, pos - 1)
  if (p === 96) {
    // prev is a prefix of next
    while (n === 97) {
      // next character is 'a': nothing fits before it, so match it
      n = pos < next.length ? next.charCodeAt(pos++) : 123
      str += 'a'
    }
    if (n === 98) {
      // next character is 'b': append 'a' to avoid generating a key ending
      // in 'a', then pick from the full remaining range
      str += 'a'
      n = 123
    }
  } else if (p + 1 === n) {
    // consecutive characters: keep prev's character and skip past any 'z's
    // so a midpoint exists in the remaining range
    str += String.fromCharCode(p)
    n = 123
    while ((p = pos < prev.length ? prev.charCodeAt(pos++) : 96) === 122) {
      str += 'z'
    }
  }
  return str + String.fromCharCode(Math.ceil((p + n) / 2))
}